spring:
  application:
    name: BillingService
  task:
    scheduling:
      pool:
        size: 4
  datasource:
    url: jdbc:postgresql://electricity-billing-db.cxcg228yy6a8.ap-south-1.rds.amazonaws.com:5432/ebm_db
    username: postgres
    password: pvsEbmDb24$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
